# 数据库连接
db_url="mysql://root:000@127.0.0.1/test"

tables=["yaf_doc_logs","yaf_doc_build","yaf_doc_clone","yaf_doc_git","yaf_doc_menu"]
tpl_body="""
#[derive(FromRow,SqlxModel,Clone,Debug,Serialize, Deserialize)]
#[sqlx_model(table_name="{table.table_name}")]
pub struct {table.model_name}Model \\{ {{ for field in field_data }} 
    {{ if field.comment }}/// {field.comment|rmln} {{ if field.default}} default:  {field.default} {{ endif }}{{ endif }}
    #[sqlx(default)]
    pub {field.column_name}: {field.type_name},
{{ endfor }}}
"""

model_name_rule="upper_camel"
model_name_start_replace="yaf_"
table_name_start_replace="yaf_"


outfile_merge=true
outfile_name="src/model/doc_model.rs"
outfile_merge_tpl="""
use sqlx::FromRow;
use sqlx_model::SqlxModel;
use serde::\\{Deserialize, Serialize};
{{ for item in items }} 
{item.render_data}
{{endfor}}
"""
outfile_overwrite=true

type_transform=true
type_default="String"
[type_map.1]
"i32"=["int\\(\\d+\\)"]
[type_map.2]
"i8"=["tinyint\\(\\d+\\)","ENUM"]
[type_map.3]
"i16"=["smallint\\(\\d+\\)"]
[type_map.4]
"i64"=["bigint\\(\\d+\\)"]
[type_map.5]
"u32"=["int\\(\\d+\\)\\s+unsigned"]
[type_map.6]
"u8"=["tinyint\\(\\d+\\)\\s+unsigned"]
[type_map.7]
"u16"=["smallint\\(\\d+\\)\\s+unsigned"]
[type_map.8]
"u64"=["bigint\\(\\d+\\)\\s+unsigned"]
[type_map.9]
"f32"=["float"]
[type_map.10]
"f64"=["decimal"]
[type_map.11]
"f64"=["decimal","double"]