#app_host="127.0.0.1"
#app_port=8080
#app_ssl_port=443

#日志配置
#log_level=sqlx_core=info,lsys_sender=debug,axtix_web=debug,actix=info,mio=error,lsys_user=trace,lsys_web=trace,lsys_core=trace,lsys_user=trace,lsys_rbac=trace,lsys_docs=trace,lsys_actix_web=trace,sqlx=trace,redis=debug
#log_dir="logs"
#log_name="std::out"
#log_gelf="127.0.0.1:12201"

#数据库配置
#database_url="mysql://root:000@127.0.0.1:3306/test"
#公共表前缀
#database_table_prefix="yaf_"
#redis 配置
#redis_url="redis://127.0.0.1/"

#rbac是否使用缓存
rbac_cache = true

#静态文件目录
ui_dir = "../../../ui/public/"
#静态文件访问路径,默认:/
#ui_path="/"
#超级管理员id
root_user_id = [1]

#语言文件目录
fluent_dir = "locale/"

#页面模板目录
tpl_dir = "static"

#地址库数据文件压缩包
area_code_db = "data/2023-7-area-code.csv.gz"
#地址库索引文件目录
# area_index_dir = "/tmp/area_index"
#地址库索引时使用内存大小
# area_index_size = 500_000_000

#ip城市数据
ip_city_db = "data/IP2LOCATION-LITE-DB11.BIN"

#发送邮件 短信 生成唯一ID用
#snowflake_machine_id=1 #最大31
#snowflake_node_id=1 #最大31

# jwt token 
app_jwt_key = "bbb" #jwt 密钥


#git doc save dir
doc_git_dir = "/tmp/"
