[workspace]
resolver = "2"
members = [
    "lsys-core",
    "lsys-rbac",
    "lsys-user",
    "lsys-app",
    "lsys-web",
    "lsys-notify",
    "lsys-sender",
	"lsys-lib-sms",
    "lsys-setting",
    "lsys-logger",
    "lsys-docs",
    "examples/*"
]