name: check lsys ui

on:
  push:
    branches: [ "main" ]
    paths:
      - 'ui/**/*'
      - '!ui/**/*.md'
      - '!ui/**/*.MD'
      - '!ui/**/*.cmd'
      - '!ui/**/.gitignore'
      - '.github/workflows/check_ui.yml'

jobs:
  ui_check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build ui
      working-directory: ./ui
      run: |
        npm install
        npx webpack
