name: rust-clippy server analyze

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**/*'
      - '!server/**/*.md'
      - '!server/**/*.MD'
      - '!server/**/*.cmd'
      - '!server/**/.gitignore'
      - '.github/workflows/rust_clippy.yml'
      
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**/*'
      - '!server/**/*.md'
      - '!server/**/*.MD'
      - '!server/**/*.cmd'
      - '!server/**/.gitignore'
      - '.github/workflows/rust_clippy.yml'
      
  schedule:
    - cron: '29 15 * * 4'

jobs:
  rust-server-clippy-analyze:
    name: Run rust-clippy analyzing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af #@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true

      - name: Install required cargo
        run: cargo install clippy-sarif sarif-fmt

      - name: Run server rust-clippy
        working-directory: ./server
        run:
          cargo clippy
          --all-features
          --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload server analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./server/rust-clippy-results.sarif
          wait-for-processing: true